# Message defining the actions and parameters supported by the AGV.

# Array of supported and/or required optional parameters.
# Optional parameters that are not listed here are assumed to be not supported
# by the AGV
#
# Field type: Required
OptionalParameter[] optional_parameters

# Array of actions with parameters supported by this AGV. This includes
# standard actions specified in VDA5050 and manufacturer-specific actions.
#
# Field type: Required
AGVAction[] agv_actions

